### ISSUE TITLE
Dude call me

### ISSUE THREAD

**Issue by adityahemanth** [adityahemanth/TimeKeeper#1]
805-284-5185

**Comment by binhanxu** [comment]
My phone dies. And that caused me phoneless for a week.

**Comment by binhanxu** [comment]
Sorry, Hemanth. My phone dies. I didn't have phone for one week. How about us meeting tomorrow after quiz? I have finished basic structure of RAFT. We could write together tomorrow.

Binhan

**Comment by binhanxu** [comment]
Tonight would still be fine. I have one chapter left to read for Quiz 4.

**Comment by adityahemanth** [comment]
Can you message me on Facebook.

**Comment by binhanxu** [comment]
Sure
